### ISSUE TITLE
BUG : Crash RSDBPersistentManager getEventsFromDB:]

### ISSUE THREAD

**Issue by WYZEYaolongZhu** [rudderlabs/rudder-sdk-ios#538] opened 2024-09-25 05:50 UTC
**Describe the bug**

 s.dependency 'Rudder', '~> 1.25'

There were few crashes before iOS 18, but a large number of crashes appeared after iOS 18. 

          Crashed: com.rudder.RSCloudModeManager
0  libsystem_malloc.dylib         0x4dc0 _xzm_xzone_malloc_tiny_outlined + 1280
1  libsqlite3.dylib               0x2ff8 sqlite3_config + 1572
2  libsqlite3.dylib               0x19ee8 sqlite3_log + 1928
3  libsqlite3.dylib               0x9b354 sqlite3_sourceid + 48392
4  libsqlite3.dylib               0x9c8f4 sqlite3_sourceid + 53928
5  libsqlite3.dylib               0x2c8b0 sqlite3_step + 5416
6  libsqlite3.dylib               0x2b748 sqlite3_step + 960
7  Rudder                         0xebd4 -[RSDBPersistentManager getEventsFromDB:] + 428
8  Rudder                         0xe920 -[RSDBPersistentManager fetchEventsFromDB:ForMode:] + 192
9  Rudder                         0x7e38 __45-[RSCloudModeManager startCloudModeProcessor]_block_invoke + 244
10 libdispatch.dylib              0x2370 _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x40d0 _dispatch_client_callout + 20
12 libdispatch.dylib              0xb6d8 _dispatch_lane_serial_drain + 744
13 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 380
14 libdispatch.dylib              0x17258 _dispatch_root_queue_drain_deferred_wlh + 288
15 libdispatch.dylib              0x16aa4 _dispatch_workloop_worker_thread + 540
16 libsystem_pthread.dylib        0x4c7c _pthread_wqthread + 288
17 libsystem_pthread.dylib        0x1488 start_wqthread + 8

**Comment by SKannaniOS** [comment] 2024-09-25 08:16
Hi Yaolong Zhu,

Thank you for raising this issue. Our team is currently investigating it and will work to resolve it as soon as possible.

**Comment by SKannaniOS** [comment] 2024-09-25 08:25
Hi Yaolong Zhu,

You’ve already shared the issue stack trace. Please provide the following additional details, as they will be very helpful in resolving the issue.

- Please explain the scenario of this issue (e.g., when the app is in the background or during a specific user action)
- Provide the exact steps to reproduce the crash
- How often does this issue occur? (e.g., every time, randomly, after specific actions)
- Is there a specific percentage or frequency of occurrence that you’ve noticed (e.g., does it happen to a large number of users or only in certain cases)?

**Comment by WYZEYaolongZhu** [comment] 2024-09-25 11:14
@SKannaniOS 

-  According to statistics, the main problem of Crash is when operating the microphone of the operating system.
- I did not reproduce it 
- this issue  occur disapper,
- Before iOS 18, counted 100+ crashes within 30 days. iOS 18 has 3,000+ crashes in 30 days

**Comment by SKannaniOS** [comment] 2024-09-25 15:22
@WYZEYaolongZhu 

Please confirm if you have encountered 3000+ instances of the same crash within the last 30 days.

**Comment by WYZEYaolongZhu** [comment] 2024-09-26 02:00
@SKannaniOS  yes

**Comment by SKannaniOS** [comment] 2024-09-26 09:51
@WYZEYaolongZhu 

- Kindly provide the device details experiencing this crash, including the model name, iOS version, and any other relevant information.
- Please provide the SDK initialization snippet as well.

**Comment by WYZEYaolongZhu** [comment] 2024-09-27 01:41
@SKannaniOS 

- 'Rudder', '1.29',

![image](https://github.com/user-attachments/assets/e3b76bc3-9bf8-4c41-9ff8-bdcae74a875f)

-  Crash info ：
`rashed: com.rudder.RSCloudModeManager
0  libsystem_malloc.dylib         0x4dc0 _xzm_xzone_malloc_tiny_outlined + 1280
1  libsqlite3.dylib               0x2ff8 sqlite3_config + 1572
2  libsqlite3.dylib               0x8ffcc sqlite3_sourceid + 2432
3  libsqlite3.dylib               0x14b78 sqlite3_exec + 50464
4  libsqlite3.dylib               0x14994 sqlite3_exec + 49980
5  libsqlite3.dylib               0xa814 sqlite3_exec + 8636
6  libsqlite3.dylib               0x98b8 sqlite3_exec + 4704
7  libsqlite3.dylib               0x8f64 sqlite3_exec + 2316
8  libsqlite3.dylib               0x8c30 sqlite3_exec + 1496
9  Rudder                         0xeb08 -[RSDBPersistentManager getEventsFromDB:] + 224
10 Rudder                         0xe920 -[RSDBPersistentManager fetchEventsFromDB:ForMode:] + 192
11 Rudder                         0x7e38 __45-[RSCloudModeManager startCloudModeProcessor]_block_invoke + 244
12 libdispatch.dylib              0x2370 _dispatch_call_block_and_release + 32
13 libdispatch.dylib              0x40d0 _dispatch_client_callout + 20
14 libdispatch.dylib              0xb6d8 _dispatch_lane_serial_drain + 744
15 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 380
16 libdispatch.dylib              0x17258 _dispatch_root_queue_drain_deferred_wlh + 288
17 libdispatch.dylib              0x16aa4 _dispatch_workloop_worker_thread + 540
18 libsystem_pthread.dylib        0x4c7c _pthread_wqthread + 288
19 libsystem_pthread.dylib        0x1488 start_wqthread + 8`

**Comment by SKannaniOS** [comment] 2024-09-27 07:50
@WYZEYaolongZhu 

Thank you for sharing the information. Our team has prioritized this issue. Kindly provide the crash file (.crash file) to help us track it more effectively.

**Comment by WYZEYaolongZhu** [comment] 2024-10-14 08:40
@SKannaniOS I have tried using version 1.29.1, but still had the same issue

  Crashed: com.rudder.RSCloudModeManager
0  libsystem_malloc.dylib         0x4dd4 _xzm_xzone_malloc_tiny_outlined + 1280
1  libsqlite3.dylib               0x2ff8 sqlite3_config + 1572
2  libsqlite3.dylib               0x19ee8 sqlite3_log + 1928
3  libsqlite3.dylib               0x9b354 sqlite3_sourceid + 48392
4  libsqlite3.dylib               0x9c8f4 sqlite3_sourceid + 53928
5  libsqlite3.dylib               0x2c8b0 sqlite3_step + 5416
6  libsqlite3.dylib               0x2b748 sqlite3_step + 960
7  Rudder                         0xecd0 -[RSDBPersistentManager getEventsFromDB:] + 480
8  Rudder                         0xe9e8 -[RSDBPersistentManager fetchEventsFromDB:ForMode:] + 192
9  Rudder                         0x7e54 __45-[RSCloudModeManager startCloudModeProcessor]_block_invoke + 272
10 libdispatch.dylib              0x2370 _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x40d0 _dispatch_client_callout + 20
12 libdispatch.dylib              0xb6d8 _dispatch_lane_serial_drain + 744
13 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 380
14 libdispatch.dylib              0x17258 _dispatch_root_queue_drain_deferred_wlh + 288
15 libdispatch.dylib              0x16aa4 _dispatch_workloop_worker_thread + 540
16 libsystem_pthread.dylib        0x4c7c _pthread_wqthread + 288
17 libsystem_pthread.dylib        0x1488 start_wqthread + 8

**Comment by SKannaniOS** [comment] 2024-10-17 07:31
@WYZEYaolongZhu 
Hi, we’ve released version 1.29.2-beta with a fix on Cocoapods. We encourage you to give it a try, as we’re confident this update addresses the crash issue.

**Comment by SKannaniOS** [comment] 2024-10-24 07:54
@WYZEYaolongZhu 
I hope the beta release has addressed the crashes. I would appreciate any updates.

**Comment by SKannaniOS** [comment] 2024-11-14 06:21
Since we’ve released a fix for this issue in the version below, we are closing the issue.

[v1.30.0](https://github.com/rudderlabs/rudder-sdk-ios/releases/tag/v1.30.0)

**Closed by SKannaniOS** 2024-11-14 06:21 UTC
