### ISSUE TITLE
Crashed on `RSContext.m - Line 92`

### ISSUE THREAD

**Issue by duyduong** [rudderlabs/rudder-sdk-ios#68] opened 2021-07-05 03:24 UTC
My company integrated with RudderStack and it crashed a lot after releasing

<img width="1245" alt="Screen Shot 2021-07-05 at 10 21 24" src="https://user-images.githubusercontent.com/450564/124413503-fc164a80-dd7a-11eb-9cca-e524fa762f44.png">

which I don't know the root cause

Is it because of not being in main-thread?

**Comment by desusai7** [comment] 2021-07-05 08:04
Hey @duyduong , It might be because of not being on the main thread. To understand it better, we would like to reproduce this issue on our end. So, Can you please help us with the following details:
1. Instrumentation you were using for making Identify calls as well as SDK initialization
2. Details about how you are initializing the Rudder iOS SDK (Generally we recommend to initialize in `didFinishLaunchingWithOptions` of `AppDelegate.m`.
3. Similarly details about how you are making `identify` calls

**Comment by duyduong** [comment] 2021-07-05 08:14
@desusai7 
1. I cannot send the instrumentation, I did not get the crash, but my users got
2. I am sure I initialized Rudder on `didFinishLaunchingWithOptions`
3. This one is not sure for this, maybe this one cause the problem
4. I am using 1.0.19

I got a clue on Crashlytics 
`crash_info_entry_0 Attempting to mutate immutable collection!`

**Comment by duyduong** [comment] 2021-07-07 05:21
@desusai7 any update on this issue?

**Comment by desusai7** [comment] 2021-07-07 05:52
@duyduong Actually we couldn't reproduce the issue from the provided information. But I suspect something is wrong with the way the identify calls are made in your case. Can you please try moving them to the main thread and check if that fixes the issue

**Comment by pallabmaiti** [comment] 2021-08-17 04:22
@duyduong have you tried the above solution & can you revert back with your feedback?

**Comment by desusai7** [comment] 2021-08-18 06:33
Hey @duyduong we are able to reproduce the issue now, and we had placed a fix for this and will be available from the latest version

**Comment by duyduong** [comment] 2021-08-18 08:09
@desusai7 Thanks, for now it is a randomly crash, but the rate is acceptable. It is good if we can fix this in the latest version

**Closed** 2021-08-23 09:29 UTC

**Comment by venkat-epifi** [comment] 2021-10-19 15:48
<img width="1075" alt="Screenshot 2021-10-19 at 21 17 42" src="https://user-images.githubusercontent.com/86950189/137946223-f1865771-6d31-483f-9b8a-753f43ef9695.png">
